[project]
name = "kitchen-monitors"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
"adafruit-circuitpython-dht>=4.0.7",
"RPi.GPIO>=0.7.1"
]
